/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10
 */
public class mediaDosAlunos extends javax.swing.JFrame {

    /**
     * Creates new form mediaDosAlunos
     */
    public mediaDosAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotulo1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        rotulo2 = new javax.swing.JLabel();
        texto2 = new javax.swing.JTextField();
        rotulo3 = new javax.swing.JLabel();
        texto3 = new javax.swing.JTextField();
        rotulo4 = new javax.swing.JLabel();
        texto4 = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        mediaAluno = new javax.swing.JLabel();
        maiorNotaAluno = new javax.swing.JLabel();
        menorNotaAluno = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        rotulo5 = new javax.swing.JLabel();
        texto5 = new javax.swing.JTextField();
        situacaoAluno = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Média do aluno");

        rotulo1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rotulo1.setText("Digite a 1º nota:");

        texto1.setBackground(new java.awt.Color(102, 153, 255));
        texto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        rotulo2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rotulo2.setText("Digite a 2º nota:");

        texto2.setBackground(new java.awt.Color(102, 153, 255));
        texto2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto2ActionPerformed(evt);
            }
        });

        rotulo3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rotulo3.setText("Digite a 3º nota:");

        texto3.setBackground(new java.awt.Color(102, 153, 255));
        texto3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        texto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto3ActionPerformed(evt);
            }
        });

        rotulo4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rotulo4.setText("Digite a 4º nota:");

        texto4.setBackground(new java.awt.Color(102, 153, 255));
        texto4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto4.setForeground(new java.awt.Color(255, 255, 255));
        texto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto4ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 102, 255));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Calcular");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 102, 255));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Limpar");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(0, 102, 255));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Sair");
        button3.setToolTipText("");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        mediaAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        maiorNotaAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menorNotaAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        title1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 102, 255));
        title1.setText("MÉDIA DO ALUNO");

        rotulo5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rotulo5.setText("Nome do aluno(a):");

        texto5.setBackground(new java.awt.Color(102, 153, 255));
        texto5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto5.setForeground(new java.awt.Color(255, 255, 255));
        texto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto5ActionPerformed(evt);
            }
        });

        situacaoAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title1)
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maiorNotaAluno)
                    .addComponent(mediaAluno)
                    .addComponent(situacaoAluno)
                    .addComponent(menorNotaAluno)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotulo4)
                            .addGap(18, 18, 18)
                            .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotulo2)
                            .addGap(18, 18, 18)
                            .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotulo1)
                            .addGap(18, 18, 18)
                            .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotulo5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(texto5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotulo3)
                        .addGap(18, 18, 18)
                        .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo5)
                    .addComponent(texto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo2)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo3)
                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo4)
                    .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1)
                    .addComponent(button2)
                    .addComponent(button3))
                .addGap(18, 18, 18)
                .addComponent(mediaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maiorNotaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menorNotaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(situacaoAluno)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto1ActionPerformed

    private void texto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto2ActionPerformed

    private void texto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto3ActionPerformed

    private void texto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto4ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        double nota1, nota2, nota3, nota4, media; // declarando variaveis do tipo double
        String nomeAluno;
        //copiando valores colocado nas caixas de texto
        nota1 = Double.parseDouble(texto1.getText());
        nota2 = Double.parseDouble(texto2.getText());
        nota3 = Double.parseDouble(texto3.getText());
        nota4 = Double.parseDouble(texto4.getText());
        nomeAluno = texto5.getText();

        media = 0; // zerando o valor da variavel média

        media = (nota1 + nota2 + nota3 + nota4) / 4; //fazendo calculo de uma média de 4 notas

        mediaAluno.setText("Média do aluno: " + media); //mostrando ao usuario o valor da média

        // verificando qual foi a MAIOR nota do usuario
        if (nota1 >= nota2 && nota1 >= nota3 && nota1 >= nota4) {
            maiorNotaAluno.setText("A maior nota é: " + nota1);
        } else if (nota2 >= nota1 && nota2 >= nota3 && nota2 >= nota4) {
            maiorNotaAluno.setText("A maior nota é: " + nota2);
        } else if (nota3 >= nota1 && nota3 >= nota2 && nota3 >= nota4) {
            maiorNotaAluno.setText("A maior nota é: " + nota3);
        } else {
            maiorNotaAluno.setText("A maior nota é: " + nota4);
        }

        //verificando qual foi a MENOR nota do usuario
        if (nota1 <= nota2 && nota1 <= nota3 && nota1 <= nota4) {
            menorNotaAluno.setText("A menor nota é: " + nota1);
        } else if (nota2 <= nota1 && nota2 <= nota3 && nota2 <= nota4) {
            menorNotaAluno.setText("A menor nota é: " + nota2);
        } else if (nota3 <= nota1 && nota3 <= nota2 && nota3 <= nota4) {
            menorNotaAluno.setText("A menor nota é: " + nota3);
        } else {
            menorNotaAluno.setText("A menor nota é: " + nota4);
        }
        
        if (media >= 7){
           situacaoAluno.setText("Situação do aluno(a)"+nomeAluno+": Aprovado");
        }
        else {
           situacaoAluno.setText("Situação do aluno(a)"+nomeAluno+": Reprovado"); 
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        texto1.setText(null);
        texto2.setText(null);
        texto3.setText(null);
        texto4.setText(null);
        texto5.setText(null);
        mediaAluno.setText(null);
        maiorNotaAluno.setText(null);
        menorNotaAluno.setText(null);
        situacaoAluno.setText(null);
        texto1.requestFocus();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    private void texto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mediaDosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mediaDosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mediaDosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mediaDosAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mediaDosAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maiorNotaAluno;
    private javax.swing.JLabel mediaAluno;
    private javax.swing.JLabel menorNotaAluno;
    private javax.swing.JLabel rotulo1;
    private javax.swing.JLabel rotulo2;
    private javax.swing.JLabel rotulo3;
    private javax.swing.JLabel rotulo4;
    private javax.swing.JLabel rotulo5;
    private javax.swing.JLabel situacaoAluno;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    private javax.swing.JTextField texto4;
    private javax.swing.JTextField texto5;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
